title: David's Log
description: A journey through x64 Assembly and world travels.
baseurl: "/blog"
url: "https://davidjerman.github.io"
author: David Jerman

remote_theme: "jekyll/minima"

plugins:
  - jekyll-remote-theme

minima:
  skin: dark

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
